services:
  - type: web
    name: event-hub-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn \"app:create_app()\" --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: RUN_MIGRATIONS
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
